INSERT INTO PREDIO(ID_PREDIO, PREDIO, DESCRICAO) VALUES(10, 'CA', 'Central de Aulas')

INSERT INTO SALA(ID_SALA, SALA, DESCRICAO, ID_PREDIO) VALUES(11, '11', 'Sala de Aula', 10)

INSERT INTO AULA(ID_AULA, AULA, DIA, HORARIO, PROFESSOR, ID_SALA) VALUES(1, 'IA', 'TER', '19h00-20h40', 'Graça', 1)

INSERT INTO USUARIO(ID_USUARIO, LOGIN, SENHA) VALUES(1, 'admin', 'admin')